export const MetaGodPower = [
    {
        name: 'Stop auto-pilote',
        description: 'Permet d’activer/désactiver l’auto-pilote.',
        image: 'assets/icon/meta/stop.png',
        level: 0,
        maxLevel: 0,
        cost: [],
    },
    {
        name: 'Offline Boost',
        description: 'Augmente vos gains hors-ligne de 10 % par niveau.',
        image: 'assets/icon/meta/offline.png',
        level: 0,
        maxLevel: 10,
        cost: [25, 50, 100, 200, 250, 400, 600, 800, 1000, 1200],
    },
    {
        name: 'XP Collector',
        description: 'Augmente vos gains d’XP de 10 % par niveau.',
        image: 'assets/icon/meta/xp.png',
        level: 0,
        maxLevel: 5,
        cost: [50, 100, 200, 400, 800],
    },
    {
        name: 'Apparition de coffres',
        description: 'Augmente la probabilité de trouver des coffres.',
        image: 'assets/icon/meta/chest.png',
        level: 0,
        maxLevel: 10,
        cost: [40, 80, 160, 320, 520, 680, 720, 120, 20, 10],
    },
    {
        name: 'Plus d’œufs',
        description: 'Augmente la probabilité de trouver des œufs.',
        image: 'assets/icon/meta/eggs.png',
        level: 0,
        maxLevel: 5,
        cost: [20, 50, 100, 120, 150],
    },
    {
        name: 'Incubateur supplémentaire',
        description: 'Non disponible.',
        image: 'assets/icon/meta/incubateur.png',
        level: 0,
        maxLevel: 0,
        cost: [],
    },
];
