import { BaseAttack, BaseAttackName, SpeAttack, SpeAttackName } from "../attack";

export const BASE_ATTACK_RECORD: Record<BaseAttackName, BaseAttack> = {
  frappe: {
    name: 'frappe',
    effiency: 20,
    type: 'neutre',
    description: 'un coup simple',
    animation: 'simple',
  },
  baffe: {
    name: 'baffe',
    effiency: 30,
    type: 'neutre',
    description: 'un coup leger mais qui fait du bruit',
    animation: 'simple',
  },
};

export const SPE_ATTACK_RECORD: Record<SpeAttackName, SpeAttack> = {
  griffure: {
    name: 'griffure',
    effect: 'multiple',
    description: 'un coup rapide repeté avec 50% echec',
    type: 'neutre',
    turn: 4,
    effiency: 10,
    probability: 0.5,
    animation: 'multiple',
  },
  attack_boost: {
    name: 'attack_boost',
    effect: 'boost',
    description: '*0.5 en attack',
    type: 'neutre',
    turn: 3,
    bonus: 0.5,
    duration: 5,
    stat: 'attack',
    animation: 'boost',
  },
  focus: {
    name: 'focus',
    effect: 'boost',
    description: '*2 damage',
    type: 'neutre',
    turn: 5,
    bonus: 2,
    duration: 1,
    stat: 'damage',
    animation: 'boost',
  },
  regen: {
    name: 'regen',
    effect: 'heal',
    description: 'un petit heal de rien du tout',
    type: 'neutre',
    turn: 3,
    effiency: 5,
    animation: 'heal',
  },
  defense_boost: {
    name: 'defense_boost',
    effect: 'boost',
    description: '*0.5 en defense',
    type: 'neutre',
    turn: 2,
    bonus: 0.5,
    duration: 5,
    stat: 'defense',
    animation: 'boost',
  },
  shield: {
    name: 'shield',
    effect: 'shield',
    description: 'un petit shield de rien du tout',
    type: 'neutre',
    turn: 4,
    effiency: 10,
    animation: 'shield',
  },
};